# Generated by Django 3.2.18 on 2023-02-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination_Name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('image', models.ImageField(default='null.jpg', upload_to='sample')),
            ],
        ),
    ]
